export interface LabelFilm {
  title: string;
  year: number;
}

export const CRITERION: LabelFilm[] = [
  { title: "Seven Samurai", year: 1954 },
  { title: "Rashomon", year: 1950 },
  { title: "The 400 Blows", year: 1959 },
  { title: "Breathless", year: 1960 },
  { title: "8½", year: 1963 },
  { title: "Persona", year: 1966 },
  { title: "The Seventh Seal", year: 1957 },
  { title: "Wild Strawberries", year: 1957 },
  { title: "Bicycle Thieves", year: 1948 },
  { title: "La Dolce Vita", year: 1960 },
  { title: "The Grand Illusion", year: 1937 },
  { title: "M", year: 1931 },
  { title: "Yojimbo", year: 1961 },
  { title: "Ikiru", year: 1952 },
  { title: "The Battle of Algiers", year: 1966 },
  { title: "Chungking Express", year: 1994 },
  { title: "In the Mood for Love", year: 2000 },
  { title: "Brazil", year: 1985 },
  { title: "Blue Velvet", year: 1986 },
  { title: "Mulholland Drive", year: 2001 },
  { title: "Ran", year: 1985 },
  { title: "Yi Yi", year: 2000 },
  { title: "Solaris", year: 1972 },
  { title: "Stalker", year: 1979 },
  { title: "Tokyo Story", year: 1953 },
  { title: "Children of Paradise", year: 1945 },
  { title: "Jules and Jim", year: 1962 },
  { title: "The Ice Storm", year: 1997 },
  { title: "Mirror", year: 1975 },
  { title: "Scenes from a Marriage", year: 1973 },
  { title: "Amarcord", year: 1973 },
  { title: "Aguirre, the Wrath of God", year: 1972 },
  { title: "Nights of Cabiria", year: 1957 },
  { title: "Au Revoir les Enfants", year: 1987 },
  { title: "A Man Escaped", year: 1956 },
  { title: "The 400 Blows", year: 1959 },
  { title: "Safe", year: 1995 },
  { title: "Short Cuts", year: 1993 },
  { title: "Eyes Without a Face", year: 1960 },
  { title: "Cleo from 5 to 7", year: 1962 },
];

export const KINO_LORBER: LabelFilm[] = [
  { title: "The White Ribbon", year: 2009 },
  { title: "Amour", year: 2012 },
  { title: "Caché", year: 2005 },
  { title: "The Piano Teacher", year: 2001 },
  { title: "Ida", year: 2013 },
  { title: "Cold War", year: 2018 },
  { title: "Portrait of a Lady on Fire", year: 2019 },
  { title: "Toni Erdmann", year: 2016 },
  { title: "Son of Saul", year: 2015 },
  { title: "Force Majeure", year: 2014 },
  { title: "The Hunt", year: 2012 },
  { title: "Nosferatu the Vampyre", year: 1979 },
  { title: "Fitzcarraldo", year: 1982 },
  { title: "Stroszek", year: 1977 },
  { title: "Ali: Fear Eats the Soul", year: 1974 },
  { title: "The Marriage of Maria Braun", year: 1979 },
  { title: "Wings of Desire", year: 1987 },
  { title: "Certified Copy", year: 2010 },
  { title: "Like Someone in Love", year: 2012 },
  { title: "This Is Not a Film", year: 2011 },
  { title: "The Turin Horse", year: 2011 },
  { title: "Werckmeister Harmonies", year: 2000 },
  { title: "The Man from London", year: 2007 },
  { title: "Bluebeard", year: 2009 },
  { title: "Los Olvidados", year: 1950 },
  { title: "Viridiana", year: 1961 },
  { title: "Belle de Jour", year: 1967 },
  { title: "The Discreet Charm of the Bourgeoisie", year: 1972 },
  { title: "My Dinner with Andre", year: 1981 },
  { title: "Vanya on 42nd Street", year: 1994 },
];
